### PR TITLE
[CIS-182] Add showConnectionErrorAlert flag to ClientLogger

### LINKED ISSUE #169: Make Connection Error Alert Optional
the Alert for Connection menu while tied only to debug seems nice it is also annoying ;)

It would be nice if this was also tied to a Logging Option to turn off

```
    static func showConnectionAlert(_ error: Error, jsonError: ClientErrorResponse?) {
        #if DEBUG
        let jsonError = jsonError ?? ClientErrorResponse(code: 0, message: "<unknown>", statusCode: 0)
        let message = "\(jsonError.message)\n\nCode: \(jsonError.code)\nStatus Code: \(jsonError.statusCode)\n\n\(error)"
        DispatchQueue.main.async {
            let alert = UIAlertController(title: "Connection Error", message: message, preferredStyle: .alert)
            alert.addAction(.init(title: "Ok, I'll check", style: .cancel, handler: nil))
            UIApplication.shared.delegate?.window??.rootViewController?.present(alert, animated: true)
        }
        #endif
    }
```

### PR DESCRIPTION
**Pull request by b-onc**
Fixes #169

### CODE REVIEW

File: Sources/Client/Client/ClientLogger.swift [hunk 1]
```diff
@@ -128,6 +128,10 @@ public final class ClientLogger {
             return intersectedOptions.isEnabled ? ClientLogger(icon: icon, level: .level(intersectedOptions)) : nil
         }
     }
+  
+    /// Controls whether connection error dialogue is shown on WebSocket errors.
+    /// you can check `showConnectionErrorAlert` function to see how the dialogue is being shown.
+    public static var showConnectionErrorAlert = false
```
Comment (VojtaStavik) [inline Sources/Client/Client/ClientLogger.swift:134]: Why did you decider to change it to `false` when the current default is `true`?

Comment (b-onc) [reply Sources/Client/Client/ClientLogger.swift:134]: Same reason as showing emoji in logging: people didn't want this on by default
