### PR TITLE
Fix emojis in reaction view displayed in inconsistent order

### LINKED ISSUE #332: ChatViewController.emojiReactionTypes display order is not consistent
## What did you do?
The displayed order of `emojiReactionTypes` is not consistent. If you display `ChatViewController` multiple times, you will get a different display order for `emojiReactionTypes` each time.

## What did you expect to happen?
The display of `emojiReactionsTypes` should be consistent for each display

## GetStream Environment
**GetStream Chat version:** 2.2.5
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:** 13.5
**Swift version:**
**Xcode version:** 11.5
**Device:** Simulator

### PR DESCRIPTION
**Pull request by cardoso**
I had to make it a little more complex than just sorting with < since that yields:
Screen Shot 2020-06-30 at 22 01 44
And that's a weird order to have. It makes more sense to have this which is in line with most social platforms:
Screen Shot 2020-06-30 at 22 39 39

Ideally, the dictionary would be an array of `(type: String, (emoji: String, maxScore: String))`, but this would break API for `defaultEmojiReactionTypes`.

Closes #332

### CODE REVIEW

File: Sources/UI/Chat/Chat View Controller/ChatViewController+Reactions.swift [hunk 1]
```diff
@@ -12,7 +12,28 @@ import StreamChatCore
...
+            case (.some(let lhs), .none):
+                return true
+            case (.none, .some(let rhs)):
+                return false
+            case (.none, .none):
+                return $0.value.emoji < $1.value.emoji
+            }
+        })
+    }
+}
```
Comment (b-onc) [inline Sources/UI/Chat/Chat View Controller/ChatViewController+Reactions.swift:36]: ❤️ to this solution!

File: Sources/UI/Views/ReactionsView.swift [hunk 2]
```diff
@@ -36,6 +36,8 @@ final class ReactionsView: UIView {
         return view
     }()
     
+    public var preferredEmojiOrder = ["👍", "❤️", "😂", "😲", "😔", "😠"]
```
Comment (b-onc) [inline Sources/UI/Views/ReactionsView.swift:39]: IMHO this should live under `ChatViewController`, close to `emojiReactionTypes` so it's easily configurable (by users using different reactions)
You can follow the same structure: `preferredEmojiOrder` as `var`, `defaultPreferredEmojiOrder` as `open` so it's used by overriding classes
