### PR TITLE
[CIS 122] Add test coverage for `Atomic`

### LINKED ISSUE #252: Crash when removing device token
## What did you do?

According to [this](https://github.com/GetStream/stream-chat-swift/wiki/Push-Notifications) wiki, it is recommended to remove a user device using the following code: 
```swift
if let currentDevice = User.current?.currentDevice {
    Client.shared.removeDevice(deviceId: currentDevice.id).subscribe().disposed(by: disposeBag)
}
```

## What did you expect to happen?

That it removes the user device from the Stream account

## What happened instead?

The app crashes in the `Atomic.swift` file from the `StreamChatClient`.

Screen Shot 2020-05-06 at 12 46 05 PM
Screen Shot 2020-05-06 at 12 47 03 PM

## GetStream Environment
**GetStream Chat version:** 2.0.1
**iOS version:** 13.3.1
**Swift version:** Swift 5
**Xcode version:** 11.4
**Device:** iPhone X

## Additional context

I have also tried this same code on the latest version of Stream (2.1.1) with the same result

### PR DESCRIPTION
**Pull request by VojtaStavik**
### In this PR:

- I created two new async assertions `AssertEqualEventually` and `AssertNilEventually`. They are inspired by [Nimble](https://github.com/Quick/Nimble) and they allow us to write async assertions as they were synchronous.

- I added a test suite for `Atomic` and changed its implementation from using `DispatchQueue` to `NSRecursiveLock`.

---

[Closes #252]

### CODE REVIEW

File: Sources/Client/Utils/Atomic.swift [hunk 1]
```diff
@@ -13,12 +13,25 @@ import Foundation
 public final class Atomic<T> {
     /// A didSet callback type.
     public typealias DidSetCallback = (_ value: T?, _ oldValue: T?) -> Void
-    
-    private let queue = DispatchQueue(label: "io.getstream.Chat.Atomic", qos: .userInitiated, attributes: .concurrent)
-    private var value: T?
+
+    private let lock = NSRecursiveLock()
+
+    private var value: T? {
```
Comment (buh) [inline Sources/Client/Utils/Atomic.swift:19]: Can we now avoid an optional type?

Comment (VojtaStavik) [reply Sources/Client/Utils/Atomic.swift:19]: Yes, it's possible but I didn't want to do it in this PR.

**Comment by VojtaStavik** [comment]
This should also fix #252

File: Sources/Client/Utils/Atomic.swift [hunk 2]
```diff
@@ -54,23 +66,10 @@ public final class Atomic<T> {
...
-        value = newValue
-        
-        if let callbackQueue = callbackQueue {
-            callbackQueue.async { [weak self] in self?.didSet?(newValue, oldValue) }
-        } else {
-            didSet?(newValue, oldValue)
-        }
+    public func update(_ changes: (T) -> T?) {
+        lock.lock()
+        value = changes(value!)
```
Comment (b-onc) [inline Sources/Client/Utils/Atomic.swift:71]: Isn't it dangerous?

File: Tests/Client/Custom Assertions/AssertEventually.swift [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+            return
+        }
+        _ = XCTWaiter.wait(for: [.init()], timeout: evaluationPeriod)
+    }
+
+    XCTAssertNil(expression(), file: file, line: line)
+}
+
+/// How big is the period between expression evaluations.
+private let evaluationPeriod: TimeInterval = 0.001
```
Comment (b-onc) [inline Tests/Client/Custom Assertions/AssertEventually.swift:66]: Can you move this up?

File: Tests/Client/Custom Assertions/AssertEventually.swift [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+/// Blocks the current test execution and periodically checks if the expression evaluates to `nil`. Fails if
+/// the expression result is not `nil` within the `timeout` period.
+///
+/// - Parameters:
+///   - expression: The expression to evaluate.
+///   - timeout: The maximum time the function waits for the expression results to equal.
+///
+/// - Warning: ⚠️ The expression is evaluated repeatedly during the function execution. It should not have
+///   any side effects which can affect its result.
+func AssertNilEventually<T>(_ expression: @autoclosure () -> T?,
```
Comment (b-onc) [inline Tests/Client/Custom Assertions/AssertEventually.swift:48]: Can't this function just call `AssertEqualEventually(expression, nil, timeout: timeout, ...)`?

File: Tests/Client/Unit Tests/AtomicTests.swift [hunk 5]
```diff
@@ -0,0 +1,234 @@
...
+
+import XCTest
+@testable import StreamChatClient
+
+class AtomicTests: XCTestCase {
+
+    func test_Atomic_whenValueChanged_callsDidSetCallback() {
+        // Setup
+        let initialValue = "Luke"
+        let newValue = "Leia"
```
Comment (b-onc) [inline Tests/Client/Unit Tests/AtomicTests.swift:16]: This PR is not opened on May 4th, hence this is invalid now 😂

File: Tests/Client/Unit Tests/AtomicTests.swift [hunk 6]
```diff
@@ -0,0 +1,234 @@
...
+        let value = Atomic(["Luke": 1])
+        XCTAssertEqual(value["Luke"], 1)
+    }
+
+    func test_Atomic_whenCalledRecursively_worksCorrectly() {
+        // Setup
+        let value = Atomic("Luke")
+
+        // Action
+        value.update { (oldValue) -> String? in
```
Comment (b-onc) [inline Tests/Client/Unit Tests/AtomicTests.swift:64]: In this test case, naming implies `value` is `String` or `oldValue` is Atomic. I suggest renaming `value` to `atomic` or `atomicValue`

File: Tests/Client/Unit Tests/AtomicTests.swift [hunk 7]
```diff
@@ -0,0 +1,234 @@
...
+    // Don't forget to increase `numberOfStressTestCycles` to some more interesting value.
+
+//    func test_Atomic_underHeavyLoad_behavesCorrently() {
+//        for _ in 0..<100 {
+//            test_Atomic_usedAsCounter_behavesCorrectly()
+//            test_Atomic_usedWithCollection_behavesCorrectly()
+//            test_Atomic_whenSetAndGetCalledSimultaneously_behavesCorrectly()
+//            test_Atomic_whenCalledFromMainThred_behavesCorrectly()
+//        }
+//    }
```
Comment (b-onc) [inline Tests/Client/Unit Tests/AtomicTests.swift:104]: Why do we need to keep this test commented?

File: Tests/Client/Unit Tests/AtomicTests.swift [hunk 8]
```diff
@@ -0,0 +1,234 @@
...
+                value -= 1
+            }
+        }
+        AssertEqualEventually(value.get(), 0)
+
+        // Check for memory leaks
+        weak var weakValue = value
+        value = nil
+
+        AssertNilEventually(weakValue)
```
Comment (b-onc) [inline Tests/Client/Unit Tests/AtomicTests.swift:129]: Why "eventually"? Shouldn't it be nil immediately?

File: Tests/Client/Unit Tests/AtomicTests.swift [hunk 9]
```diff
@@ -0,0 +1,234 @@
...
+        value.append(to: \.elements, 2)
+        XCTAssertEqual(value.get(), Helper(elements: [1, 2]))
+    }
+
+    func test_Atomic_dictionaryHelpers() {
+        let value = Atomic(["Luke": 1])
+        XCTAssertEqual(value["Luke"], 1)
+    }
+
+    func test_Atomic_whenCalledRecursively_worksCorrectly() {
```
Comment (b-onc) [inline Tests/Client/Unit Tests/AtomicTests.swift:59]: I think these `behavesCorrectly`, `worksCorrectly` suffixes do not add any value to test names, obviously tests will check correct behavior. For example, for this test I'd suggest `test_Atomic_recurviseCalls`
For `test_Atomic_usedAsCounter_behavesCorrectly` -> `test_Atomic_usedAsCounter`
same for similar names

File: Sources/Client/Utils/Atomic.swift (hunk 2 above)
Comment (VojtaStavik) [reply Sources/Client/Utils/Atomic.swift:71]: YES! It's a leftover from my experiments. Thanks for finding it!

File: Tests/Client/Custom Assertions/AssertEventually.swift (hunk 4 above)
Comment (VojtaStavik) [reply Tests/Client/Custom Assertions/AssertEventually.swift:48]: It probably can. I have more async assertions like these coming in the PR with device tests. I think the proper solution is to extract the "waiter" logic and reuse it. In this case, a copy-paste solution was easier.
I'll fix it in the follow-up PR with the additional assertions.

File: Tests/Client/Unit Tests/AtomicTests.swift (hunk 5 above)
Comment (VojtaStavik) [reply Tests/Client/Unit Tests/AtomicTests.swift:16]: I find StarWars to be an excellent source of "dummy" data! So many names of characters, planets, ships, etc ...

Comment (b-onc) [reply Tests/Client/Unit Tests/AtomicTests.swift:16]: Love it! To turn up the creativity to 11:
```swift
let initialValue = "Anakin"
let newValue = "Darth Vader"
```
😂

File: Tests/Client/Unit Tests/AtomicTests.swift (hunk 7 above)
Comment (VojtaStavik) [reply Tests/Client/Unit Tests/AtomicTests.swift:104]: Because it can take tens of seconds to run. We don't need to run the stress tests every time if nothing has changed in `Atomic`. We still run the tests, but only once and for `numberOfStressTestCycles: 50` so obvious regressions will be caught.

`test_Atomic_underHeavyLoad_behavesCorrently` is meant to be used only if you changed something in `Atomic` and you want to be sure it behaves correctly under extreme load.

File: Tests/Client/Unit Tests/AtomicTests.swift (hunk 8 above)
Comment (VojtaStavik) [reply Tests/Client/Unit Tests/AtomicTests.swift:129]: I noticed that for the original `DispatchQueue`-based solution the denin wasn't often happening immediately but (probably) in the next run loop. I didn't want to be that strict with tests here to allow alternative implementations. What's important is that it _eventually_ gets released :)

File: Tests/Client/Unit Tests/AtomicTests.swift (hunk 5 above)
Comment (VojtaStavik) [reply Tests/Client/Unit Tests/AtomicTests.swift:16]: I think we need a new "spoiler alert" badge for our PR now!

File: Tests/Client/Unit Tests/AtomicTests.swift (hunk 7 above)
Comment (b-onc) [reply Tests/Client/Unit Tests/AtomicTests.swift:104]: Got it! Maybe we can add a comment on why they should be kept disabled?

File: Tests/Client/Unit Tests/AtomicTests.swift (hunk 8 above)
Comment (b-onc) [reply Tests/Client/Unit Tests/AtomicTests.swift:129]: If it's being released immediately in the new implementation, I'd say we can assume that's the expected behavior from now on. Something not being deallocated unexpectedly might lead to issues

File: Tests/Client/Unit Tests/AtomicTests.swift (hunk 7 above)
Comment (VojtaStavik) [reply Tests/Client/Unit Tests/AtomicTests.swift:104]: Actually, I just found out it's ok to have it uncommented if `numberOfStressTestCycles` is this small. I'll change the documentation to reflect this.

File: Tests/Client/Unit Tests/AtomicTests.swift (hunk 8 above)
Comment (VojtaStavik) [reply Tests/Client/Unit Tests/AtomicTests.swift:129]: I just checked and even the current implementation is not released immediately 100% of the time so I have to keep it as-is. Not a big deal really.
