### PR TITLE
Fix image & video uploads from camera

### LINKED ISSUE #236: ChatViewController `Upload from a camera` is not work(2.1.0)
## What did you do?
After updated to 2.1.0, `Upload from a camera` doesn't work anymore.
The same is 2.1.1.
I set it back to 2.0.0 and it worked correctly.

## What did you expect to happen?
That a photo I took will be attached to the message

## What happened instead?
When I take a photo and return to the chat screen
I get the following error log and the photo is not attached.
> File URL cannot be determined for file named: photo_2020_05_03_205602.jpg

## GetStream Environment
**GetStream Chat version:** 2.1.0
**iOS version:** 13.3.1
**Swift version:** 5.1
**Xcode version:** 11.3.1
**Device:** iPhone 11 Pro

## Additional context
none

### PR DESCRIPTION
**Pull request by b-onc**
Since images coming from camera have no local fileURL, our uploads were failing. I've moved the size check logic into UploadingItem, now size check is being done on uploadingItem.data
Moreover, we've broken video uploads some time in the past and this PR fixes them too. Tested and working.
Fixes #236

### CODE REVIEW

File: Sources/Core/Presenter/UploadingItem.swift [hunk 1]
```diff
@@ -118,12 +119,13 @@ public final class UploadingItem: Equatable {
...
     }
-    
+
     /// Init an uploader item with a given uploaded file.
     ///
     /// - Parameters:
     ///   - attachment: an uploaded file attachment.
     ///   - fileName: an uploaded file name.
+    @available(*, deprecated, message: "Please use `init(channel:url:)` initializer")
     public init(attachment: Attachment, fileName: String) {
```
Comment (buh) [inline Sources/Core/Presenter/UploadingItem.swift:129]: @b-onc why you deprecate this and method above? :)
It should be used for items that were uploaded, e.g. reused in collection cells.

File: Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift [hunk 2]
```diff
@@ -466,34 +466,33 @@ extension ChatViewController {
...
+                let extraData = presenter.imageAttachmentExtraDataCallback?(pickedImage.fileURL,
+                                                                            image,
+                                                                            pickedImage.isVideo,
+                                                                            presenter.channel)
                 
-                if let fileSize = fileSizeResource.fileSize,
-                   fileSize >= 20 * 1_048_576 { // 20 MB Upload limit
+                let uploaderItem = try UploadingItem(channel: presenter.channel, pickedImage: pickedImage, extraData: extraData)
+                
+                guard let data = uploaderItem.data, data.count < 20 * 1024 * 1024 else {
```
Comment (buh) [inline Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift:480]: I thought you'll update a file size inside `UploadingItem`. So we won't need to read full file data (for URL case) to get the size of it.

File: Sources/Core/Presenter/UploadingItem.swift (hunk 1 above)
Comment (b-onc) [reply Sources/Core/Presenter/UploadingItem.swift:129]: But they're not used? At least I couldn't find where they're used. Can you point me?

File: Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift (hunk 2 above)
Comment (b-onc) [reply Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift:480]: `UploadingItem` will parse the `data` for uploading anyway, we can use `data.count` to get the size easily.

File: Sources/Core/Presenter/UploadingItem.swift (hunk 1 above)
Comment (buh) [reply Sources/Core/Presenter/UploadingItem.swift:129]: You're right. I can't find them in usage. My example was wrong. I think it was supposed to be used for editing messages where you already have uploaded attachments and can delete them, but it wasn't implemented. On edit, users can only edit text or remove a message completely.

Comment (b-onc) [reply Sources/Core/Presenter/UploadingItem.swift:129]: Thank you for explaining! 🙌
