### PR TITLE
Fix queryUsers not encoding sorting

### LINKED ISSUE #324: [UsersQuery] missing Sort encoding
## What did you do?
Trying to sort users using queryUsers

## What did you expect to happen?
Users to be sorted with `Sorting` I used

## What happened instead?
Users are sorted by `created_at` key instead

## Additional context
It seems that encode method in `UsersQuery` does not encode `sort`.

### PR DESCRIPTION
**Pull request by b-onc**
Fixes #324 

**DoD**:
- [x] Docs updated

### CODE REVIEW

File: Sources/Client/Client/Client+User.swift [hunk 1]
```diff
@@ -25,7 +41,11 @@ public extension Client {
                     pagination: Pagination = [.usersPageSize],
                     options: QueryOptions = [],
                     _ completion: @escaping Client.Completion<[User]>) -> Cancellable {
-        queryUsers(query: .init(filter: filter, sort: sort, pagination: pagination, options: options), completion)
+        if let sort = sort {
+            return queryUsers(query: .init(filter: filter, sorting: [sort], pagination: pagination, options: options), completion)
+        } else {
+            return queryUsers(query: .init(filter: filter, sorting: [], pagination: pagination, options: options), completion)
+        }
```
Comment (buh) [inline Sources/Client/Client/Client+User.swift:48]:
```suggestion
queryUsers(query: .init(filter: filter, sorting: (sort == nil ? [] : [sort!]),  pagination: pagination,  options: options), 
           completion)
```

File: Sources/Client/Model/User/UsersQuery.swift [hunk 2]
```diff
@@ -57,11 +62,27 @@ public struct UsersQuery: Encodable {
...
+    ///   - filter: filter conditions, e.g. `"name".equal(to: "rover_curiosity")`
+    ///   - sort: sort options, e.g. `.init("last_active", isAscending: false)`
+    ///   - pagination: Pagination for query. Only supports `.limit` and `.offset`
+    ///   - options: Query options, e.g. `.presence`
+    public init(filter: Filter, sort: Sorting? = nil, pagination: Pagination = [.usersPageSize], options: QueryOptions = []) {
+        if let sort = sort {
+            self.init(filter: filter, sorting: [sort], pagination: pagination, options: options)
+        } else {
+            self.init(filter: filter, sorting: [], pagination: pagination, options: options)
+        }
```
Comment (buh) [inline Sources/Client/Model/User/UsersQuery.swift:77]: the same suggestion as above

File: Sources/Core/Client/Client+RxUser.swift [hunk 3]
```diff
@@ -24,7 +37,11 @@ public extension Reactive where Base == Client {
                     sort: Sorting? = nil,
                     pagination: Pagination = [.usersPageSize],
                     options: QueryOptions = []) -> Observable<[User]> {
-        queryUsers(query: .init(filter: filter, sort: sort, pagination: pagination, options: options))
+        if let sort = sort {
+            return queryUsers(query: .init(filter: filter, sorting: [sort], pagination: pagination, options: options))
+        } else {
+            return queryUsers(query: .init(filter: filter, sorting: [], pagination: pagination, options: options))
+        }
```
Comment (buh) [inline Sources/Core/Client/Client+RxUser.swift:44]: the same suggestion as above

File: Sources/Client/Client/Client+User.swift (hunk 1 above)
Comment (b-onc) [reply Sources/Client/Client/Client+User.swift:48]: Actually that was my first code, but I hate force unwrapping in production even when it's 100% safe so I went this route. A bit more code but 1000% safe (irrationally so)

Comment (buh) [reply Sources/Client/Client/Client+User.swift:48]: Force unwrap is always a warning for developers. In this case it's pretty clear because it's small case `sort == nil ? [] : [sort!]`
