### PR TITLE
[CIS-1627] Fix MessageSearchController not respecting sorting

### LINKED ISSUE #1821: ChatMessageSearchController's sorting is not working
## What did you do?
I searched message by using ChatMessageSearchController
```Swift
let query = MessageSearchQuery(
    channelFilter: .equal(.cid, to: cid),
    messageFilter: .and([.autocomplete(.text, text: query)]),
    sort: [.init(key: .id, isAscending: false)]
  )
messageSearchController = client.messageSearchController()
messageSearchController.search(query: query)
```

## What did you expect to happen?
I expected the results to be sorted in descending order of created time

## What happened instead?
The results were the same(in ascending order) regardless of the `sort` (`sort: [ .init(key: .id, isAscending: false)]` and `sort: [ .init(key: .id, isAscending: true)]` result was same)
Am I using the wrong query????

## GetStream Environment
**GetStream Chat version:** 4.10.1
**GetStream Chat frameworks:** StreamChat
**iOS version:** 15.x, 14.x
**Swift version:** 5.5.2
**Xcode version:** 13.2.1
**Device:** all of iPhone, iPad supporting iOS 14+

### PR DESCRIPTION
**Pull request by b-onc**
### 🔗 Issue Link
CIS-1627
Fixes #1821

### 🎯 Goal

`MessageSearchController` has various issues:
1. It doesn't clear old search results when a new search is made
1. It doesn't respect `sort` passed from user
1. It's not unit tested
1. It makes empty search queries which results in 400 error returned from BE

### 🛠 Implementation

Implementation is now very similar to `UserSearchController`, with `sort` obtained from `query.sort` and `UpdatePolicy` reused.

### 📝 Changes

Unit tests are added, sort param is now respected, search results are now cleared, and empty searches are avoided.

### 🧪 Testing

There's a search option in `SwiftUI` demo (in `SampleApp`) if anyone wants interactive testing.

### ☑️ Contributor Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] Changelog is updated with client-facing changes
- [x] New code is covered by unit tests
- [x] This change follows zero ⚠️ policy (required)
- [x] Affected documentation updated (docusaurus, tutorial, CMS)

### CODE REVIEW

File: Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController.swift [hunk 1]
```diff
@@ -162,19 +171,25 @@ public class ChatMessageSearchController: DataController, DelegateCallable, Data
...
         query.filterHash = explicitFilterHash
         
         lastQuery = query
         
-        messageUpdater.search(query: query) { error in
+        // To respect sorting the user passed, we must reset messagesObserver
+        state = .initialized
+        setMessagesObserver()
+        _messagesObserver.reset()
+        startObserversIfNeeded()
```
Comment (nuno-vieira) [inline Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController.swift:190]: Maybe we can extract this to an helper function `resetMessageObserver()` ?

File: Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController_Tests.swift [hunk 2]
```diff
@@ -0,0 +1,649 @@
+//
+// Copyright © 2022 Stream.io Inc. All rights reserved.
+//
+
+import Foundation
+@testable import StreamChat
+@testable import StreamChatTestTools
+import XCTest
+
+class MessageSearchController_Tests: XCTestCase {
```
Comment (nuno-vieira) [inline Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController_Tests.swift:10]: Nice!

File: Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController_Tests.swift [hunk 3]
```diff
@@ -0,0 +1,649 @@
...
+    override func tearDown() {
+        controllerCallbackQueueID = nil
+        
+        env.messageUpdater?.cleanUp()
+        
+        AssertAsync {
+            Assert.canBeReleased(&controller)
+            Assert.canBeReleased(&client)
+            Assert.canBeReleased(&env)
+        }
```
Comment (nuno-vieira) [inline Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController_Tests.swift:46]: I would be careful in using this. When I fixed some memory leaks in the previous PR, this `Assert.canBeReleased()` function was not actually catching the memory leak.

File: Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController_Tests.swift [hunk 4]
```diff
@@ -0,0 +1,649 @@
...
+        
+        let filterHash = controller.query.filterHash
+        // Deallocate controller
+        controller = nil
+        
+        // Assert query doesn't exist in DB anymore
+        AssertAsync.willBeNil(client.databaseContainer.viewContext.messageSearchQuery(filterHash: filterHash))
+        
+        // Assert the message is still here
+        AssertAsync.staysTrue(message != nil)
```
Comment (nuno-vieira) [inline Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController_Tests.swift:94]: If our goal in the future is to move away from `AssertAsync` I think it would be better to stop using it for new tests. Not going to ask you to re-write all these tests ofc, but I think it is worth keeping that in mind for the future.

File: Sources/StreamChat/Query/MessageSearchQuery.swift [hunk 5]
```diff
@@ -4,9 +4,52 @@
...
     case relevance
+    
+    /// Sort messages by their `id`.
     case id
+    
+    /// Sort messages by their `created_at` dates.
+    case createdAt
+    
+    /// Sort messages by their `updated_at` dates.
+    case updatedAt
```
Comment (nuno-vieira) [inline Sources/StreamChat/Query/MessageSearchQuery.swift:20]: Isn't this a breaking change? 🤔 Well, in practice, no one should be using a switch case for this... This is a hint that this should be a Static String like we use already in other places.

File: Sources/StreamChat/Workers/MessageUpdater.swift [hunk 6]
```diff
@@ -563,11 +563,16 @@ class MessageUpdater: Worker {
         })
     }
     
-    func search(query: MessageSearchQuery, completion: ((Error?) -> Void)? = nil) {
+    func search(query: MessageSearchQuery, policy: UpdatePolicy = .merge, completion: ((Error?) -> Void)? = nil) {
```
Comment (nuno-vieira) [inline Sources/StreamChat/Workers/MessageUpdater.swift:566]: Any reason for the default argument? Since this is an internal API, the default argument might hide an important decision in a Higher Level API.

**Review by nuno-vieira — COMMENTED** [review]
Looks good to me Overall 👍 Just added some questions and small comments, after that should be ✅

File: Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController.swift [hunk 7]
```diff
@@ -141,13 +141,22 @@ public class ChatMessageSearchController: DataController, DelegateCallable, Data
             completion?(ClientError.CurrentUserDoesNotExist("For message search with text, a current user must be logged in"))
             return
         }
+        // We don't choose `guard` here since the expression
+        // guard !text.isEmpty, lastQuery != nil else { ...clearSearch(for: lastQuery!).. }
+        // would be much more complex to parse than this `if` statement
```
[the remark this answers is not in the document]
Comment (b-onc) [reply Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController.swift:146]: I don't think it's very apparent here, so I decided to comment the reasoning. There's nothing wrong with decision comments IMHO

File: Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController_Tests.swift (hunk 3 above)
Comment (b-onc) [reply Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController_Tests.swift:46]: Here, it works as expected

File: Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController_Tests.swift (hunk 4 above)
Comment (b-onc) [reply Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController_Tests.swift:94]: Tests are mostly copy/paste from `UserSearchController_Tests`

File: Sources/StreamChat/Query/MessageSearchQuery.swift (hunk 5 above)
Comment (b-onc) [reply Sources/StreamChat/Query/MessageSearchQuery.swift:20]: ¯\_(ツ)_/¯

File: Sources/StreamChat/Workers/MessageUpdater.swift (hunk 6 above)
Comment (b-onc) [reply Sources/StreamChat/Workers/MessageUpdater.swift:566]: To mirror `UserListUpdater`, no strong reason here

File: Sources/StreamChat/Query/MessageSearchQuery.swift (hunk 5 above)
Comment (nuno-vieira) [reply Sources/StreamChat/Query/MessageSearchQuery.swift:20]: No need to change this tho, don't think it is blocking 👍

File: Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController_Tests.swift (hunk 4 above)
Comment (nuno-vieira) [reply Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController_Tests.swift:94]: I see, makes sense then

**Review by nuno-vieira — APPROVED** [review]
LGTM! ✅ Would be nice to extract the `resetMessagesObserver()`. But other than that, LGTM.
